theme: jekyll-theme-minimal
title: CIT 281 - Project 6
description: I gained more experience creating and working classes with inheritance, creating and working with classes, debugging code, using a generic block of code to process data, interpreting functional descriptions and specifications to complete an assignment, writing and executing non-web server Node.js JavaScript code using VSCode, using modern JavaScript syntax, and working with static data.
